### ISSUE TITLE
We are going to use the helm-adapter. Please look at the following issues.

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/helm-adapter#83]
There are few issues:
 - [x] The URL for uploading the tgz archive must be the same as that for downloading the package,the domain name prefix needs to be dynamically combined during download. https://github.com/artipie/helm-adapter/issues/96
 - [x] A method for obtaining indexYaml based on the prefix needs to be added. #90 
 - [x] IndexYaml need delete chart, please provide methods deleteByName and deleteByNameAndVersion #84 
 - [x] Provide a method to merge multiple index Yaml files. The repo agent will use it. #89 
 - [x] Set TgzArchive and ChartYaml to public. Otherwise, the function cannot be invoked.
 - [x] An example of invoking an interface is provided. We use spring instead of vertx: https://github.com/artipie/helm-adapter/issues/97

**Comment by g4s8** [comment]
@genryxy could you please decompose it into multiple tickets?

**Comment by genryxy** [comment]
@g4s8 there are two items left from this list of requirements. Corresponding issues were created
